# This is a basic workflow to help you get started with Actions

name: Black

on: [push]


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start job
        run: echo start job

      - name: Run a multi-line script
        run: |
            pip3 install black
            black .
